databases:
  - name: airbnbclone
    databaseName: airbnbclone
    user: airbnbclone

services:
  - type: web
    name: airbnbclone
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: airbnbclone
          property: connectionString
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4